### ISSUE TITLE
Add support for CK_LWS_TUNER_TYPE

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-request-asplos18-mobilenets-armcl-opencl#13]
Arm prefer to benchmark ArmCL with the LWS tuner enabled. So we should add support for the same tuner types (`NONE`, `BIFROST`, `DEFAULT`), and do a warm up run in the setup region when the dynamic (`DEFAULT`) tuner is requested: https://github.com/ctuning/ck-nntest/blob/master/program/conv-armcl-opencl/conv.cpp#L119

**Comment by psyhtest** [comment]
Another thing to ensure is that the `reshape_to_columns` kernel used in GEMM-based convolution is only called once in the setup region: https://github.com/ctuning/ck-nntest/blob/master/program/conv-armcl-opencl/conv.cpp#L113

**Comment by Chunosov** [comment]
> reshape_to_columns kernel used in GEMM-based convolution is only called once in the setup region

As they said here https://github.com/ARM-software/ML-ArmNN-collaboration/pull/58#issuecomment-410216465
> If you're using the Graph API it will be called automatically as part of the finalise() stage

and we do finalization now (https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl/blob/cc7b5355d127089e0e204743c618ed52ee54678a/program/mobilenets-armcl-opencl/mobilenet.cpp#L216)
```
#if defined(ARMCL_18_05_PLUS)
    // Finalize graph
    GraphConfig config {};
    graph.finalize(target_hint, config);
#endif
```

**Comment by Chunosov** [comment]
Done here https://github.com/ctuning/ck-math/commit/5617326274e20874dc87a047e1b09d9c00bc526d
and here https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl/pull/14

**Comment by psyhtest** [comment]
Thanks!
