### ISSUE TITLE
Add support for CK_DATA_LAYOUT

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-request-asplos18-mobilenets-armcl-opencl#15]

**Comment by psyhtest** [comment]
v18.08 now supports NHWC in addition to NCHW with noticeable performance improvements. We should add data layout selection to the program similar to https://github.com/ctuning/ck-nntest/pull/22.

**Comment by Chunosov** [comment]
Data layout support added for `ck-math:program:armcl-classification-mobilenet` here: https://github.com/ctuning/ck-math/pull/33

**Comment by Chunosov** [comment]
Data layout support added for `ck-request-asplos18-mobilenets-armcl-opencl:program:mobilenets-armcl-opencl` here: https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl/pull/16

**Comment by psyhtest** [comment]
Thanks, merged! Will test shortly.

**Comment by Chunosov** [comment]
Only note that `armcl-classification-mobilenet` doesn't work with 18.08 because of https://github.com/ctuning/ck-math/issues/32 (and only 18.08 supports `NHWC`). But `mobilenets-armcl-opencl` works fine.
